import Head from "next/head";
import {
  Button,
  Stack,
  ThemeProvider,
  Box,
  Container,
  Grid,
  Paper,
} from "@mui/material";
import theme from "@/themes";
import { SignupForm } from "@/components/SignupForm";
import { LoginForm } from "@/components/LoginForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        {/*
        <Container maxWidth="xs">
          <Stack
            sx={{
              px: 2,
              height: "100vh",
              bgcolor: "primary.main",
            }}
            alignItems="center"
            justifyContent="space-around"
          >
            <Box>
              <Button variant="contained">Hello World</Button>
            </Box>
            <Box>
              <Button variant="contained">Hello World Hello!!!!</Button>
            </Box>
            <Box>
              <Button variant="contained">Hello!</Button>
            </Box>
            <Stack
              direction="row"
              width="100%"
              spacing={2}
              justifyContent="flex-end"
              alignItems="flex-end"
            >
              <Box>
                <Button variant="contained">Hello World</Button>
              </Box>
              <Box>
                <Button sx={{ height: "100px" }} variant="contained">
                  Hello World
                </Button>
              </Box>
            </Stack>
          </Stack>
        </Container>
        */}
        <Container maxWidth="md">
          <SignupForm />
        </Container>
      </ThemeProvider>
    </>
  );
}
